[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","W","I"]
ignore = ["E501"]
extend-select = ["B", "C"]
extend-ignore = []

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]
"app/__init__.py" = ["F401"]
